schema_version = "1.0.0"

id = "blender_to_unity_fbx_exporter"
version = "1.0.0"
name = "Blender to Unity FBX Exporter"
tagline = "Enhanced Unity FBX Exporter"
maintainer = "Simon Nordon"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://www.yourwebsite_with_documentation.com/"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-2.0-or-later"]